"""Ingestion schema.

Revision ID: 0002_ingestion_schema
Revises: 0001_baseline

Adds the Phase 1 ingestion tables: seasons, locations, meetings, rounds,
sessions, drivers, teams, seat_entries, results, sync_conflicts.

Two things here are not stock autogenerate output and must survive any future
regeneration:

  1. `meetings.deadline_session_id` is a deferred foreign key to `sessions`.
     The reference is circular at table level — sessions belong to rounds,
     rounds to meetings — so the constraint is added after both tables exist.
     Alembic's autogenerate silently omits `use_alter` constraints, so this
     ALTER is written by hand.

  2. `uq_sync_conflict_open` is a PARTIAL unique index, unique only where
     `resolved_at IS NULL`. That is what lets a twice-daily sync bump an
     existing open conflict instead of inserting a duplicate every twelve
     hours, while still allowing the same conflict to recur after resolution.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0002_ingestion_schema"
down_revision = "0001_baseline"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_driver_id', sa.String(length=64), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('code', sa.String(length=8), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drivers_provider_driver_id'), ['provider_driver_id'], unique=True)

    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_location_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('country_name', sa.String(length=80), nullable=True),
    sa.Column('country_two_code', sa.String(length=2), nullable=True),
    sa.Column('country_three_code', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_locations_provider_location_id'), ['provider_location_id'], unique=True)

    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_season_id', sa.String(length=64), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=32), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year')
    )
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seasons_provider_season_id'), ['provider_season_id'], unique=True)

    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_team_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('short_name', sa.String(length=80), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_provider_team_id'), ['provider_team_id'], unique=True)

    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline_session_id', sa.Integer(), nullable=True),
    sa.Column('grouping_locked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'sequence', name='uq_meeting_season_sequence')
    )
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meetings_deadline_at'), ['deadline_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_meetings_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meetings_season_id'), ['season_id'], unique=False)

    op.create_table('seat_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('participation_rounds', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'driver_id', 'team_id', name='uq_seat_entry')
    )
    with op.batch_alter_table('seat_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seat_entries_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seat_entries_season_id'), ['season_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seat_entries_team_id'), ['team_id'], unique=False)

    op.create_table('rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('provider_event_id', sa.String(length=64), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('number_in_meeting', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(length=24), nullable=False),
    sa.Column('format_locked', sa.Boolean(), nullable=False),
    sa.Column('provider_name', sa.String(length=200), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('scoring_ruleset_version', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'round_number', name='uq_round_season_number')
    )
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rounds_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_rounds_meeting_id'), ['meeting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rounds_provider_event_id'), ['provider_event_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_rounds_season_id'), ['season_id'], unique=False)

    op.create_table('sync_conflicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('occurrences', sa.Integer(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('resolution_note', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_conflicts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_conflicts_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_conflicts_meeting_id'), ['meeting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_conflicts_season_id'), ['season_id'], unique=False)
        batch_op.create_index('uq_sync_conflict_open', ['fingerprint'], unique=True, postgresql_where=sa.text('resolved_at IS NULL'))

    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('provider_session_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('stage', sa.String(length=24), nullable=False),
    sa.Column('stage_index', sa.Integer(), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('results_ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_provider_session_id'), ['provider_session_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_sessions_round_id'), ['round_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_start_time'), ['start_time'], unique=False)

    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('provider_result_id', sa.String(length=64), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('grid_position', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('points', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fastest_lap_rank', sa.Integer(), nullable=True),
    sa.Column('car_number', sa.Integer(), nullable=True),
    sa.Column('lap_time', sa.String(length=24), nullable=True),
    sa.Column('display_time', sa.String(length=24), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'driver_id', name='uq_result_session_driver')
    )
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.create_index('ix_result_season_driver', ['season_id', 'driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_results_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_results_provider_result_id'), ['provider_result_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_results_season_id'), ['season_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_results_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_results_team_id'), ['team_id'], unique=False)

    # Deferred foreign key: `meetings` is created before `sessions`, so this
    # cannot be inlined above. Autogenerate omits use_alter constraints.
    op.create_foreign_key(
        "fk_meetings_deadline_session",
        "meetings", "sessions",
        ["deadline_session_id"], ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade():
    op.drop_constraint("fk_meetings_deadline_session", "meetings", type_="foreignkey")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_results_team_id'))
        batch_op.drop_index(batch_op.f('ix_results_session_id'))
        batch_op.drop_index(batch_op.f('ix_results_season_id'))
        batch_op.drop_index(batch_op.f('ix_results_provider_result_id'))
        batch_op.drop_index(batch_op.f('ix_results_driver_id'))
        batch_op.drop_index('ix_result_season_driver')

    op.drop_table('results')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_start_time'))
        batch_op.drop_index(batch_op.f('ix_sessions_round_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_provider_session_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('sync_conflicts', schema=None) as batch_op:
        batch_op.drop_index('uq_sync_conflict_open', postgresql_where=sa.text('resolved_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_sync_conflicts_season_id'))
        batch_op.drop_index(batch_op.f('ix_sync_conflicts_meeting_id'))
        batch_op.drop_index(batch_op.f('ix_sync_conflicts_kind'))

    op.drop_table('sync_conflicts')
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rounds_season_id'))
        batch_op.drop_index(batch_op.f('ix_rounds_provider_event_id'))
        batch_op.drop_index(batch_op.f('ix_rounds_meeting_id'))
        batch_op.drop_index(batch_op.f('ix_rounds_date'))

    op.drop_table('rounds')
    with op.batch_alter_table('seat_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seat_entries_team_id'))
        batch_op.drop_index(batch_op.f('ix_seat_entries_season_id'))
        batch_op.drop_index(batch_op.f('ix_seat_entries_driver_id'))

    op.drop_table('seat_entries')
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meetings_season_id'))
        batch_op.drop_index(batch_op.f('ix_meetings_location_id'))
        batch_op.drop_index(batch_op.f('ix_meetings_deadline_at'))

    op.drop_table('meetings')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_provider_team_id'))

    op.drop_table('teams')
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seasons_provider_season_id'))

    op.drop_table('seasons')
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations_provider_location_id'))

    op.drop_table('locations')
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drivers_provider_driver_id'))

    op.drop_table('drivers')
    # ### end Alembic commands ###
